jaffle_shop_metrics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: <host>
      user: postgres
      password: <pass>
      port: 5432
      dbname: "{{env_var('DBT_DB')}}"
      schema: public
      threads: 4
