jaffle_shop_metrics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: alex-scannerdev-postgres.cimx6f5bfg6p.ap-southeast-2.rds.amazonaws.com
      user: postgres
      password: 27nawcUeWtnVwDfy
      port: 5432
      dbname: postgres
      schema: public
      threads: 4